version: "3.9"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  number-generator:
    build: .
    ports:
      - "8090:8080"
    depends_on:
      - redis
    environment:
      RUST_LOG: actix_web=debug,actix_server=info
